// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.2
// source: ddss.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "cn.edu.ustc.kclab.ddss";

/** 引擎类型 */
export enum EngineKind {
  /** EAGER - 积极模式：主动搜索数据 */
  EAGER = 0,
  /** LAZY - 惰性模式：被动响应查询 */
  LAZY = 1,
  UNRECOGNIZED = -1,
}

export function engineKindFromJSON(object: any): EngineKind {
  switch (object) {
    case 0:
    case "EAGER":
      return EngineKind.EAGER;
    case 1:
    case "LAZY":
      return EngineKind.LAZY;
    case -1:
    case "UNRECOGNIZED":
    default:
      return EngineKind.UNRECOGNIZED;
  }
}

export function engineKindToJSON(object: EngineKind): string {
  switch (object) {
    case EngineKind.EAGER:
      return "EAGER";
    case EngineKind.LAZY:
      return "LAZY";
    case EngineKind.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** 节点信息 */
export interface Node {
  /** 节点唯一标识符 */
  id: string;
  /** 节点地址（格式: IP:端口） */
  addr: string;
}

/** 加入集群请求 */
export interface JoinRequest {
  /** 请求加入的节点信息 */
  node: Node | undefined;
}

/** 加入集群响应 */
export interface JoinResponse {
  /** 当前集群中所有节点的列表 */
  nodes: Node[];
}

/** 离开集群请求 */
export interface LeaveRequest {
  /** 请求离开的节点信息 */
  node: Node | undefined;
}

/** 离开集群响应 */
export interface LeaveResponse {
}

/** 引擎元数据 */
export interface EngineMetaData {
  /** 引擎标识符 */
  id: string;
  /** 引擎类型 */
  kind: EngineKind;
  /** 输入数据模式列表 */
  input: string[];
  /** 输出数据模式列表 */
  output: string[];
}

/** 获取元数据请求 */
export interface MetaDataRequest {
}

/** 获取元数据响应 */
export interface MetaDataResponse {
  /** 引擎元数据信息 */
  metadata: EngineMetaData | undefined;
}

/** 推送数据请求 */
export interface PushDataRequest {
  /** 要推送的数据列表 */
  data: string[];
}

/** 推送数据响应 */
export interface PushDataResponse {
}

/** 拉取数据请求 */
export interface PullDataRequest {
}

/** 拉取数据响应 */
export interface PullDataResponse {
  /** 返回的数据列表 */
  data: string[];
}

function createBaseNode(): Node {
  return { id: "", addr: "" };
}

export const Node: MessageFns<Node> = {
  encode(message: Node, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.addr !== "") {
      writer.uint32(18).string(message.addr);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Node {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNode();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.addr = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Node {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      addr: isSet(object.addr) ? globalThis.String(object.addr) : "",
    };
  },

  toJSON(message: Node): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.addr !== "") {
      obj.addr = message.addr;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Node>, I>>(base?: I): Node {
    return Node.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Node>, I>>(object: I): Node {
    const message = createBaseNode();
    message.id = object.id ?? "";
    message.addr = object.addr ?? "";
    return message;
  },
};

function createBaseJoinRequest(): JoinRequest {
  return { node: undefined };
}

export const JoinRequest: MessageFns<JoinRequest> = {
  encode(message: JoinRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.node !== undefined) {
      Node.encode(message.node, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JoinRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJoinRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.node = Node.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JoinRequest {
    return { node: isSet(object.node) ? Node.fromJSON(object.node) : undefined };
  },

  toJSON(message: JoinRequest): unknown {
    const obj: any = {};
    if (message.node !== undefined) {
      obj.node = Node.toJSON(message.node);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<JoinRequest>, I>>(base?: I): JoinRequest {
    return JoinRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JoinRequest>, I>>(object: I): JoinRequest {
    const message = createBaseJoinRequest();
    message.node = (object.node !== undefined && object.node !== null) ? Node.fromPartial(object.node) : undefined;
    return message;
  },
};

function createBaseJoinResponse(): JoinResponse {
  return { nodes: [] };
}

export const JoinResponse: MessageFns<JoinResponse> = {
  encode(message: JoinResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.nodes) {
      Node.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JoinResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJoinResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.nodes.push(Node.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JoinResponse {
    return { nodes: globalThis.Array.isArray(object?.nodes) ? object.nodes.map((e: any) => Node.fromJSON(e)) : [] };
  },

  toJSON(message: JoinResponse): unknown {
    const obj: any = {};
    if (message.nodes?.length) {
      obj.nodes = message.nodes.map((e) => Node.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<JoinResponse>, I>>(base?: I): JoinResponse {
    return JoinResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JoinResponse>, I>>(object: I): JoinResponse {
    const message = createBaseJoinResponse();
    message.nodes = object.nodes?.map((e) => Node.fromPartial(e)) || [];
    return message;
  },
};

function createBaseLeaveRequest(): LeaveRequest {
  return { node: undefined };
}

export const LeaveRequest: MessageFns<LeaveRequest> = {
  encode(message: LeaveRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.node !== undefined) {
      Node.encode(message.node, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LeaveRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLeaveRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.node = Node.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LeaveRequest {
    return { node: isSet(object.node) ? Node.fromJSON(object.node) : undefined };
  },

  toJSON(message: LeaveRequest): unknown {
    const obj: any = {};
    if (message.node !== undefined) {
      obj.node = Node.toJSON(message.node);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LeaveRequest>, I>>(base?: I): LeaveRequest {
    return LeaveRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LeaveRequest>, I>>(object: I): LeaveRequest {
    const message = createBaseLeaveRequest();
    message.node = (object.node !== undefined && object.node !== null) ? Node.fromPartial(object.node) : undefined;
    return message;
  },
};

function createBaseLeaveResponse(): LeaveResponse {
  return {};
}

export const LeaveResponse: MessageFns<LeaveResponse> = {
  encode(_: LeaveResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LeaveResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLeaveResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): LeaveResponse {
    return {};
  },

  toJSON(_: LeaveResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<LeaveResponse>, I>>(base?: I): LeaveResponse {
    return LeaveResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LeaveResponse>, I>>(_: I): LeaveResponse {
    const message = createBaseLeaveResponse();
    return message;
  },
};

function createBaseEngineMetaData(): EngineMetaData {
  return { id: "", kind: 0, input: [], output: [] };
}

export const EngineMetaData: MessageFns<EngineMetaData> = {
  encode(message: EngineMetaData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.kind !== 0) {
      writer.uint32(16).int32(message.kind);
    }
    for (const v of message.input) {
      writer.uint32(26).string(v!);
    }
    for (const v of message.output) {
      writer.uint32(34).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EngineMetaData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEngineMetaData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.kind = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.input.push(reader.string());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.output.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EngineMetaData {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      kind: isSet(object.kind) ? engineKindFromJSON(object.kind) : 0,
      input: globalThis.Array.isArray(object?.input) ? object.input.map((e: any) => globalThis.String(e)) : [],
      output: globalThis.Array.isArray(object?.output) ? object.output.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: EngineMetaData): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.kind !== 0) {
      obj.kind = engineKindToJSON(message.kind);
    }
    if (message.input?.length) {
      obj.input = message.input;
    }
    if (message.output?.length) {
      obj.output = message.output;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EngineMetaData>, I>>(base?: I): EngineMetaData {
    return EngineMetaData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EngineMetaData>, I>>(object: I): EngineMetaData {
    const message = createBaseEngineMetaData();
    message.id = object.id ?? "";
    message.kind = object.kind ?? 0;
    message.input = object.input?.map((e) => e) || [];
    message.output = object.output?.map((e) => e) || [];
    return message;
  },
};

function createBaseMetaDataRequest(): MetaDataRequest {
  return {};
}

export const MetaDataRequest: MessageFns<MetaDataRequest> = {
  encode(_: MetaDataRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MetaDataRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMetaDataRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MetaDataRequest {
    return {};
  },

  toJSON(_: MetaDataRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MetaDataRequest>, I>>(base?: I): MetaDataRequest {
    return MetaDataRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MetaDataRequest>, I>>(_: I): MetaDataRequest {
    const message = createBaseMetaDataRequest();
    return message;
  },
};

function createBaseMetaDataResponse(): MetaDataResponse {
  return { metadata: undefined };
}

export const MetaDataResponse: MessageFns<MetaDataResponse> = {
  encode(message: MetaDataResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.metadata !== undefined) {
      EngineMetaData.encode(message.metadata, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MetaDataResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMetaDataResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.metadata = EngineMetaData.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MetaDataResponse {
    return { metadata: isSet(object.metadata) ? EngineMetaData.fromJSON(object.metadata) : undefined };
  },

  toJSON(message: MetaDataResponse): unknown {
    const obj: any = {};
    if (message.metadata !== undefined) {
      obj.metadata = EngineMetaData.toJSON(message.metadata);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MetaDataResponse>, I>>(base?: I): MetaDataResponse {
    return MetaDataResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MetaDataResponse>, I>>(object: I): MetaDataResponse {
    const message = createBaseMetaDataResponse();
    message.metadata = (object.metadata !== undefined && object.metadata !== null)
      ? EngineMetaData.fromPartial(object.metadata)
      : undefined;
    return message;
  },
};

function createBasePushDataRequest(): PushDataRequest {
  return { data: [] };
}

export const PushDataRequest: MessageFns<PushDataRequest> = {
  encode(message: PushDataRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.data) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PushDataRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePushDataRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PushDataRequest {
    return { data: globalThis.Array.isArray(object?.data) ? object.data.map((e: any) => globalThis.String(e)) : [] };
  },

  toJSON(message: PushDataRequest): unknown {
    const obj: any = {};
    if (message.data?.length) {
      obj.data = message.data;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PushDataRequest>, I>>(base?: I): PushDataRequest {
    return PushDataRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PushDataRequest>, I>>(object: I): PushDataRequest {
    const message = createBasePushDataRequest();
    message.data = object.data?.map((e) => e) || [];
    return message;
  },
};

function createBasePushDataResponse(): PushDataResponse {
  return {};
}

export const PushDataResponse: MessageFns<PushDataResponse> = {
  encode(_: PushDataResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PushDataResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePushDataResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): PushDataResponse {
    return {};
  },

  toJSON(_: PushDataResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<PushDataResponse>, I>>(base?: I): PushDataResponse {
    return PushDataResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PushDataResponse>, I>>(_: I): PushDataResponse {
    const message = createBasePushDataResponse();
    return message;
  },
};

function createBasePullDataRequest(): PullDataRequest {
  return {};
}

export const PullDataRequest: MessageFns<PullDataRequest> = {
  encode(_: PullDataRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PullDataRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePullDataRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): PullDataRequest {
    return {};
  },

  toJSON(_: PullDataRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<PullDataRequest>, I>>(base?: I): PullDataRequest {
    return PullDataRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PullDataRequest>, I>>(_: I): PullDataRequest {
    const message = createBasePullDataRequest();
    return message;
  },
};

function createBasePullDataResponse(): PullDataResponse {
  return { data: [] };
}

export const PullDataResponse: MessageFns<PullDataResponse> = {
  encode(message: PullDataResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.data) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PullDataResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePullDataResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PullDataResponse {
    return { data: globalThis.Array.isArray(object?.data) ? object.data.map((e: any) => globalThis.String(e)) : [] };
  },

  toJSON(message: PullDataResponse): unknown {
    const obj: any = {};
    if (message.data?.length) {
      obj.data = message.data;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PullDataResponse>, I>>(base?: I): PullDataResponse {
    return PullDataResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PullDataResponse>, I>>(object: I): PullDataResponse {
    const message = createBasePullDataResponse();
    message.data = object.data?.map((e) => e) || [];
    return message;
  },
};

export type ClusterService = typeof ClusterService;
export const ClusterService = {
  /** 向对方节点发送加入请求, 对方负责将本节点信息加入其本地信息, 并返回当前集群中所有节点的信息, 由本节点负责向其他节点发送加入请求 */
  join: {
    path: "/cn.edu.ustc.kclab.ddss.Cluster/Join",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: JoinRequest): Buffer => Buffer.from(JoinRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): JoinRequest => JoinRequest.decode(value),
    responseSerialize: (value: JoinResponse): Buffer => Buffer.from(JoinResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): JoinResponse => JoinResponse.decode(value),
  },
  /** 向对方节点发送离开请求, 对方负责将本节点信息从其本地信息中删除, 由本节点负责向所有节点发送离开请求 */
  leave: {
    path: "/cn.edu.ustc.kclab.ddss.Cluster/Leave",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: LeaveRequest): Buffer => Buffer.from(LeaveRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): LeaveRequest => LeaveRequest.decode(value),
    responseSerialize: (value: LeaveResponse): Buffer => Buffer.from(LeaveResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): LeaveResponse => LeaveResponse.decode(value),
  },
} as const;

export interface ClusterServer extends UntypedServiceImplementation {
  /** 向对方节点发送加入请求, 对方负责将本节点信息加入其本地信息, 并返回当前集群中所有节点的信息, 由本节点负责向其他节点发送加入请求 */
  join: handleUnaryCall<JoinRequest, JoinResponse>;
  /** 向对方节点发送离开请求, 对方负责将本节点信息从其本地信息中删除, 由本节点负责向所有节点发送离开请求 */
  leave: handleUnaryCall<LeaveRequest, LeaveResponse>;
}

export interface ClusterClient extends Client {
  /** 向对方节点发送加入请求, 对方负责将本节点信息加入其本地信息, 并返回当前集群中所有节点的信息, 由本节点负责向其他节点发送加入请求 */
  join(request: JoinRequest, callback: (error: ServiceError | null, response: JoinResponse) => void): ClientUnaryCall;
  join(
    request: JoinRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: JoinResponse) => void,
  ): ClientUnaryCall;
  join(
    request: JoinRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: JoinResponse) => void,
  ): ClientUnaryCall;
  /** 向对方节点发送离开请求, 对方负责将本节点信息从其本地信息中删除, 由本节点负责向所有节点发送离开请求 */
  leave(
    request: LeaveRequest,
    callback: (error: ServiceError | null, response: LeaveResponse) => void,
  ): ClientUnaryCall;
  leave(
    request: LeaveRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: LeaveResponse) => void,
  ): ClientUnaryCall;
  leave(
    request: LeaveRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: LeaveResponse) => void,
  ): ClientUnaryCall;
}

export const ClusterClient = makeGenericClientConstructor(
  ClusterService,
  "cn.edu.ustc.kclab.ddss.Cluster",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): ClusterClient;
  service: typeof ClusterService;
  serviceName: string;
};

export type EngineService = typeof EngineService;
export const EngineService = {
  /** 获取引擎的元数据信息 */
  metaData: {
    path: "/cn.edu.ustc.kclab.ddss.Engine/MetaData",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: MetaDataRequest): Buffer => Buffer.from(MetaDataRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): MetaDataRequest => MetaDataRequest.decode(value),
    responseSerialize: (value: MetaDataResponse): Buffer => Buffer.from(MetaDataResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): MetaDataResponse => MetaDataResponse.decode(value),
  },
  /** 推送数据到对方, 对方不负责转发到其他节点 */
  pushData: {
    path: "/cn.edu.ustc.kclab.ddss.Engine/PushData",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: PushDataRequest): Buffer => Buffer.from(PushDataRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): PushDataRequest => PushDataRequest.decode(value),
    responseSerialize: (value: PushDataResponse): Buffer => Buffer.from(PushDataResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): PushDataResponse => PushDataResponse.decode(value),
  },
  /** 从对方拉取先前所有数据, 对方不负责收集其他节点数据 */
  pullData: {
    path: "/cn.edu.ustc.kclab.ddss.Engine/PullData",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: PullDataRequest): Buffer => Buffer.from(PullDataRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): PullDataRequest => PullDataRequest.decode(value),
    responseSerialize: (value: PullDataResponse): Buffer => Buffer.from(PullDataResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): PullDataResponse => PullDataResponse.decode(value),
  },
} as const;

export interface EngineServer extends UntypedServiceImplementation {
  /** 获取引擎的元数据信息 */
  metaData: handleUnaryCall<MetaDataRequest, MetaDataResponse>;
  /** 推送数据到对方, 对方不负责转发到其他节点 */
  pushData: handleUnaryCall<PushDataRequest, PushDataResponse>;
  /** 从对方拉取先前所有数据, 对方不负责收集其他节点数据 */
  pullData: handleUnaryCall<PullDataRequest, PullDataResponse>;
}

export interface EngineClient extends Client {
  /** 获取引擎的元数据信息 */
  metaData(
    request: MetaDataRequest,
    callback: (error: ServiceError | null, response: MetaDataResponse) => void,
  ): ClientUnaryCall;
  metaData(
    request: MetaDataRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: MetaDataResponse) => void,
  ): ClientUnaryCall;
  metaData(
    request: MetaDataRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: MetaDataResponse) => void,
  ): ClientUnaryCall;
  /** 推送数据到对方, 对方不负责转发到其他节点 */
  pushData(
    request: PushDataRequest,
    callback: (error: ServiceError | null, response: PushDataResponse) => void,
  ): ClientUnaryCall;
  pushData(
    request: PushDataRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: PushDataResponse) => void,
  ): ClientUnaryCall;
  pushData(
    request: PushDataRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: PushDataResponse) => void,
  ): ClientUnaryCall;
  /** 从对方拉取先前所有数据, 对方不负责收集其他节点数据 */
  pullData(
    request: PullDataRequest,
    callback: (error: ServiceError | null, response: PullDataResponse) => void,
  ): ClientUnaryCall;
  pullData(
    request: PullDataRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: PullDataResponse) => void,
  ): ClientUnaryCall;
  pullData(
    request: PullDataRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: PullDataResponse) => void,
  ): ClientUnaryCall;
}

export const EngineClient = makeGenericClientConstructor(EngineService, "cn.edu.ustc.kclab.ddss.Engine") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): EngineClient;
  service: typeof EngineService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
